"""initial schema

Revision ID: 15e9f8163fce
Revises: 
Create Date: 2026-07-03 09:44:31.431439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15e9f8163fce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pmid', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('nct_id', sa.String(), nullable=True),
    sa.Column('semantic_scholar_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('authors', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('journal_issn', sa.String(), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('publication_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_retracted', sa.Boolean(), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi'),
    sa.UniqueConstraint('nct_id'),
    sa.UniqueConstraint('pmid'),
    sa.UniqueConstraint('semantic_scholar_id')
    )
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mesh_id', sa.String(), nullable=True),
    sa.Column('canonical_label', sa.String(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mesh_id')
    )
    op.create_table('change_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('NEW_PAPER', 'CONSENSUS_UPDATED', 'CONTRADICTION_FLAGGED', 'PAPER_RETRACTED', name='changeeventtype'), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consensus_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('consensus_text', sa.String(), nullable=True),
    sa.Column('is_insufficient_evidence', sa.Boolean(), nullable=False),
    sa.Column('supporting_paper_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('contradiction_notes', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'topic_id')
    )
    op.create_table('scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('study_type', sa.Enum('META_ANALYSIS', 'SYSTEMATIC_REVIEW', 'RCT', 'COHORT', 'CASE_CONTROL', 'CASE_SERIES', 'OPINION_EDITORIAL', 'UNKNOWN', name='studytype'), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('journal_sjr', sa.Float(), nullable=True),
    sa.Column('base_score', sa.Float(), nullable=False),
    sa.Column('risk_of_bias_flags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('evidence_tier', sa.Enum('ESTABLISHED', 'EMERGING', 'SPECULATIVE', name='evidencetier'), nullable=False),
    sa.Column('quality_breakdown', sa.String(), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('paper_topics')
    op.drop_table('consensus_snapshots')
    op.drop_table('change_events')
    op.drop_table('topics')
    op.drop_table('papers')
    # ### end Alembic commands ###
