"""journal sjr

Revision ID: 241290b8babf
Revises: 15e9f8163fce
Create Date: 2026-07-03 10:06:42.127231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241290b8babf'
down_revision: Union[str, Sequence[str], None] = '15e9f8163fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_sjr',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issn', sa.String(), nullable=False),
    sa.Column('journal_name', sa.String(), nullable=False),
    sa.Column('sjr_score', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issn', 'year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_sjr')
    # ### end Alembic commands ###
