"""citation tracking tables

Revision ID: 9c65f4e6b959
Revises: 5d7c21d9f44e
Create Date: 2026-08-06 00:04:52.723773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c65f4e6b959'
down_revision: Union[str, Sequence[str], None] = '5d7c21d9f44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citation_refresh_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('papers_refreshed', sa.Integer(), nullable=False),
    sa.Column('papers_failed', sa.Integer(), nullable=False),
    sa.Column('batches_attempted', sa.Integer(), nullable=False),
    sa.Column('rate_limit_events', sa.Integer(), nullable=False),
    sa.Column('anomalies_detected', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name', name='uq_citation_refresh_job')
    )
    op.create_table('citation_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('influential_citation_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('is_anomalous', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'observed_on', 'source', name='uq_citation_snapshot_paper_day_source')
    )
    op.create_index('ix_citation_snapshots_paper_observed', 'citation_snapshots', ['paper_id', 'observed_at'], unique=False)
    op.create_table('citation_velocity_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('velocity_per_30d', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('window_start_observed_at', sa.DateTime(), nullable=True),
    sa.Column('window_end_observed_at', sa.DateTime(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(), nullable=True),
    sa.Column('percentile', sa.Integer(), nullable=True),
    sa.Column('cohort_size', sa.Integer(), nullable=False),
    sa.Column('cohort_key', sa.String(), nullable=True),
    sa.Column('refresh_status', sa.String(), nullable=False),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', name='uq_citation_velocity_paper')
    )
    op.create_index('ix_citation_velocity_cohort', 'citation_velocity_cache', ['cohort_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # DESTRUCTIVE AND IRREVERSIBLE. citation_snapshots is the system of record for
    # citation history; Semantic Scholar reports only current counts, so dropped
    # snapshots cannot be re-derived from any source. To disable the feature
    # operationally, set CITATION_TRACKING_ENABLED=false instead of downgrading.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_citation_velocity_cohort', table_name='citation_velocity_cache')
    op.drop_table('citation_velocity_cache')
    op.drop_index('ix_citation_snapshots_paper_observed', table_name='citation_snapshots')
    op.drop_table('citation_snapshots')
    op.drop_table('citation_refresh_state')
    # ### end Alembic commands ###
